# Generated by Django 2.2.24 on 2022-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20221025_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(verbose_name='Новостройка'),
        ),
    ]
