# Generated by Django 3.2 on 2022-10-28 07:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221026_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО владельца:')),
                ('pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер телефона:')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Номер телефона:')),
                ('flats', models.ManyToManyField(related_name='flat_owners', to='property.Flat')),
            ],
        ),
    ]
