# Generated by Django 3.2 on 2022-10-28 11:48

from django.db import migrations


def connect_owners_to_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        owner = Owner.objects.get(name=flat.owner,
                                  phonenumber=flat.owners_phonenumber)

        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221028_1125'),
    ]

    operations = [
        migrations.RunPython(connect_owners_to_flats)
    ]
